### ISSUE TITLE
Set Scripting Name value on add methods

### ISSUE THREAD

**Issue by HighHarmonics2** [shakfu/py2max#4]
Is it possible to add Scripting Name when adding an object? I tried this and it didn't work:

`p.add('umenu', items=['one','two', 'three'], ScriptingName='umenu1')`

The object was added successfully, no errors. 

Scripting Name is needed when using pattrstorage with autopattr. I use this combination on most of my Max patches now. 

If this is not supported, could Scripting Name assignment be added as a new feature?

**Comment by shakfu** [comment]
@HighHarmonics2 

For such questions, what you should do in general is to create the simplest possible `<name>.maxpat` file to demonstrate your requirement using the Max application and then save the file. Then look at the `.maxpat` file in an editor and see how the changes you made are implemented in the `.maxpat` file.

So for the above requirement, create a single object in a Max file (let's say a `[cycle~]`) and populate the scripting name of the object from the Max application's inspector (let's say 'osc1') and then save. Then look at the file that was created in an editor and you will find that the `Scripting Name` field is implemented as `varname` in the `.maxpat` file.

So from py2max, you would then do the following to give an object a 'scripting name':

```python
from py2max import Patcher
p = Patcher("outputs/test_scripting_name.maxpat")
p.add_textbox('cycle~ 440', varname='osc1')
p.save()
```

Incidentally, I have added the above case as a test (see `tests/test_scripting_name.py`)

You maybe thinking why we don't implement a `scripting_name` keyword api that maps between `scripting_name` and `varname` at the py2max level. The answer is because the current py2max implementation tries to minimally reflect the lower-level api of a `.maxpat` file and if you make a change in a py2max program you should be able to immediately check if that change is reflected in the `.maxpat` file. The tradeoff is that you have to remember that `varname` is mapped to `Scripting Name` in the Max Application.

It may be that in the future, one can implement  a higher-level py2max api which reflects the api from the Max Application side. In this case you would use `scripting_name` rather than `varname`, but underneath the lower-level part of py2max would still be generating `varname`.

**Comment by HighHarmonics2** [comment]
Thanks. I appreciate the detailed description. And it is helpful to know there is an easy way to find and specify additional values.
