### ISSUE TITLE
Adding attributes to add_gen

### ISSUE THREAD

**Issue by HighHarmonics2** [shakfu/py2max#6]
Is it  possible to add attributes when calling add_gen/add_gen_tilde?

I would like to do this:

```
p = py2max.Patcher(maxFileName, layout="vertical")
sbox = p.add_gen_tilde('@title windowSync')
sbox2 = p.add_gen_tilde('@gen windowSync2.gendsp')
```

When I try this I get a TypeError:  Patcher.add_gen_tilde() takes 1 positional argument but 2 were given

**Comment by shakfu** [comment]
I suggest you do what you want in a Max patch and ensure thet it works. Then save it and look at it in a code editor. Since it's just a JSON file, you should be able to find the object(s) you are looking for.

Then try to do the same in py2max, and note that you can alway extend any py2max method by custom keyword arguments which should which will be reflected in the the generated .maxpat file. 

So from the above process, you should be be able to do what you want.

**Comment by shakfu** [comment]
@HighHarmonics2 

My bad, that's a bug. I've just committed a fix so you should be able to do what you were trying to do above without issues. 

I've also updated `tests/test_gen.py` to reflect this change:

```python
from py2max import Patcher


def test_gen():
    p = Patcher('outputs/test_gen.maxpat')
    sbox = p.add_gen("@title windowSync")
    sp = sbox.subpatcher
    i3 = sp.add_textbox('in 3')
    i4 = sp.add_textbox('in 4')
    plus = sp.add_textbox('+')
    sp.add_line(i3, plus)
    sp.add_line(i4, plus)
    p.save()


def test_gen_tilde():
    p = Patcher('outputs/test_gen_tilde.maxpat')
    sbox = p.add_gen_tilde("@nocache 0") # also p.add_gen(tilde=True)
    sp = sbox.subpatcher
    i1 = sp.add_textbox('in 1')
    i2 = sp.add_textbox('in 2')
    o1 = sp.add_textbox('out 1')
    plus = sp.add_textbox('+')
    sp.add_line(i1, plus)
    sp.add_line(i2, plus, inlet=1)
    sp.add_line(plus, o1)
    p.save()
```
